docs: add > openstad-app@0.9.0 db:install /Users/daanrosbergen/Code/openstad-app > node install-databases.js
### 1. Create and fill tables API Database
### 2.1 Create tables Auth Database
Using environment: development

Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
Error: Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_MySQL._driver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:31:12)
    at Client_MySQL.initializeDriver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:231:26)
    at Client_MySQL.Client (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:69:10)
    at new Client_MySQL (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js:53:28)
    at initKnex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js:57:10)

### 2.2 Fill tables Auth Database
Using environment: development

Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
Error: Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_MySQL._driver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:31:12)
    at Client_MySQL.initializeDriver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:231:26)
    at Client_MySQL.Client (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:69:10)
    at new Client_MySQL (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js:53:28)
    at initKnex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js:57:10)

### 3.1 Create tables Image Database
Using environment: development

Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
Error: Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_MySQL._driver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:31:12)
    at Client_MySQL.initializeDriver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:231:26)
    at Client_MySQL.Client (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:69:10)
    at new Client_MySQL (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js:53:28)
    at initKnex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js:57:10)

### 3.2 Fille tables Image Database
Using environment: development

Knex: run
$ npm install mysql --save
Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
Error: Cannot find module 'mysql'
Require stack:
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/index.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/knex.js
- /Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_MySQL._driver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:31:12)
    at Client_MySQL.initializeDriver (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:231:26)
    at Client_MySQL.Client (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/client.js:69:10)
    at new Client_MySQL (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/dialects/mysql/index.js:20:10)
    at Knex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/lib/knex.js:53:28)
    at initKnex (/Users/daanrosbergen/Code/openstad-app/node_modules/knex/bin/cli.js:57:10) step